Repository jethronap/jstat-gui, pull requests merged in 2020-02, with the labels that each got.

#30 #29 Integrate mongodb backend
  README.md
  guides/mongo/integrate_mongo.md
  pom.xml
  src/main/java/detail/compute/ComputationModelType.java
  src/main/java/detail/compute/DescriptiveStatistics.java
  src/main/java/detail/config/JStatGuiGlobalData.java
  src/main/java/detail/config/JStatInitialize.java
  src/main/java/detail/models/EDAResultModel.java
  src/main/java/detail/tasks/ComputeDescriptiveStatisticsTask.java
  src/main/java/detail/tasks/ComputeTasksController.java
  src/main/java/detail/tasks/TaskBase.java
  src/main/java/detail/tasks/utils/DescriptiveStatisticsDBWritePolicy.java
  src/main/java/detail/tasks/utils/IDBWritePolicy.java
  src/main/java/detail/tasks/utils/TaskUtils.java
  src/main/java/detail/wrappers/AnalysisFormWrapper.java
  src/main/java/detail/wrappers/EDAAnalysisFormWrapper.java
  src/main/java/gui/Analysis.java
  src/main/java/gui/AnalysisResult.java
  src/main/java/gui/JStatGuiApplication.java
  src/main/java/gui/LoadDataSet.java
  src/main/java/mongodb/ComputeResultDocBase.java
  src/main/java/mongodb/ComputeTasksControllerDoc.java
  src/main/java/mongodb/DescriptiveStatisticsResultDoc.java
  src/main/java/mongodb/IDoc.java
  src/main/java/mongodb/MongoConfig.java
  src/main/resources/application.properties
  src/main/resources/templates/analysis_eda.html
  src/main/resources/templates/analysis_result_descriptive_stats.html
  src/test/java/mongodb/DescriptiveStatisticsResultDocTest.java
  src/test/java/mongodb/mocks/ComputeResultsCollectionMock.java
  src/test/java/mongodb/mocks/IMongoDBCollectionMock.java
  src/test/java/mongodb/mocks/MongoDBCollectionMockFactory.java
  src/test/java/mongodb/mocks/MongoDBMock.java
Labels: enhancement

#31 Descriptive stats controller
  pom.xml
  src/main/java/detail/compute/ParseUtils.java
  src/main/java/detail/config/JStatGuiGlobalData.java
  src/main/java/detail/tasks/ComputeDescriptiveStatisticsTask.java
  src/main/java/detail/tasks/LoadDataSetTask.java
  src/main/java/detail/tasks/TaskBase.java
  src/main/java/detail/wrappers/StatisticsWrapper.java
  src/main/java/gui/Analysis.java
  src/main/java/gui/AnalysisResult.java
  src/main/java/gui/controllers/EDAController.java
  src/main/java/gui/controllers/EDAResultController.java
  src/main/java/gui/controllers/JstatGuiIndexController.java
  src/main/java/gui/controllers/LoadDataSetController.java
  src/main/java/gui/controllers/QuitController.java
  src/main/resources/static/css/main.css
  src/main/resources/templates/analysis.html
  src/main/resources/templates/analysis_eda.html
  src/main/resources/templates/analysis_index.html
  src/main/resources/templates/analysis_result_descriptive_stats.html
  src/main/resources/templates/eda_view.html
  src/main/resources/templates/eda_view_results.html
  src/main/resources/templates/fragments/footer.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/fragments/select_dataset.html
  src/main/resources/templates/index.html
  src/main/resources/templates/load_dataset.html
  src/main/resources/templates/quit_view.html
  src/test/java/gui/controllers/JStatGuiApplicationTests.java
  src/test/java/gui/controllers/JStatGuiIndexTest.java
Labels: Analysis, enhancement

#36 #32 refactored wrappers package
  src/main/java/gui/controllers/EDAController.java
  src/main/java/gui/controllers/EDAResultController.java
  src/main/java/gui/controllers/LoadDataSetController.java
  src/main/java/gui/wrappers/AnalysisFormWrapper.java
  src/main/java/gui/wrappers/EDAAnalysisFormWrapper.java
  src/main/java/gui/wrappers/FileWrapper.java
  src/main/java/gui/wrappers/StatisticsWrapper.java
Labels: refactoring
